---
version: "3.9"
services:
  practica_01:
    hostname: practica01
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PSGL_PASSWORD: ${PSGL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    hostname: postgres
    # platform: linux/amd64
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: practica_01
      POSTGRES_PASSWORD: ${PSGL_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "psql", "-l", "|", "grep", "practica_01"]
      interval: 30s
      timeout: 10s
      retries: 5
  front_end:
    hostname: frontend
    restart: on-failure
    build:
      context: ./front_end/
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - practica_01
